services:
  - type: web
    name: tienda-web
    env: python
    # Comandos de build: instala dependencias, aplica migraciones y recoge estáticos
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    # Comando para arrancar tu app
    startCommand: gunicorn tienda.wsgi
    # Después del despliegue, crea el superusuario si no existe
    postdeploy: |
      python manage.py shell << 'EOF'
from django.contrib.auth.models import User
if not User.objects.filter(username='admin').exists():
    User.objects.create_superuser(
      'super123',
      'victorrigocl@gmail.com',
      'Elolvidado21?'
    )
EOF
    # Variables de entorno adicionales (puedes definirlas también en el Dashboard)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-gob-db
          property: connectionString