version: 1

services:
  - type: web
    name: tienda-web
    env: python

    # Variables de entorno
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-gob-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "proyectogob-1.onrender.com,localhost,127.0.0.1"

    # Build: instala dependencias, aplica migraciones y recoge estáticos
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput

    # Start: migra de nuevo y arranca Gunicorn
    startCommand: |
      python manage.py migrate --noinput
      gunicorn tienda.wsgi:application

    # Hook tras el despliegue: crea superusuario si no existe
    deployCommand: |
      python manage.py shell << 'EOF'
      from django.contrib.auth.models import User
      if not User.objects.filter(username='super123').exists():
          User.objects.create_superuser(
              'super123',
              'victorrigocl@gmail.com',
              'Elolvidado21?'
          )
      EOF
