version: 1

services:
  - type: web
    name: tienda-web
    env: python

    # Variables de entorno
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-gob-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "proyectogob-1.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SUPERUSER_USERNAME
        value: super123
      - key: DJANGO_SUPERUSER_EMAIL
        value: victorrigocl@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Elolvidado21?

    # Build: instala deps, migra, collectstatic y crea el superuser
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py createsuperuser --noinput

    # Arranque: solo Gunicorn
    startCommand: |
      gunicorn tienda.wsgi:application
