# Generated by Django 5.0.14 on 2025-04-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleboleta',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(max_length=50, verbose_name='Tipo de usuario'),
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='DetalleBoleta',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
