# Generated by Django 5.0.14 on 2025-04-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_options_remove_perfil_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
    ]
