# Generated by Django 5.0.14 on 2025-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_empresa',
            field=models.CharField(default='Default_Empresa', max_length=100, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=15, verbose_name='Rut de la empresa'),
        ),
    ]
