# Generated by Django 5.0.14 on 2025-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfil_nombre_empresa_alter_perfil_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre_empresa',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=15, unique=True, verbose_name='Rut de la empresa'),
        ),
    ]
