# Generated by Django 5.0.14 on 2025-05-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_perfil_nombre_empresa_alter_perfil_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='codigo',
            field=models.IntegerField(default='1', unique=True, verbose_name='Código de pregunta'),
            preserve_default=False,
        ),
    ]
