# Generated by Django 5.0.14 on 2025-05-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pregunta_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='codigo',
            new_name='codi',
        ),
    ]
