# Generated by Django 5.0.14 on 2025-05-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_codi_pregunta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='id de pregunta'),
        ),
    ]
