# Generated by Django 4.2.13 on 2025-05-18 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_alter_pregunta_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.encuesta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('encuesta', 'pregunta')},
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='usuario',
        ),
    ]
