# Generated by Django 4.2.13 on 2025-05-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_encuesta_alter_respuesta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.encuesta'),
        ),
    ]
