# Generated by Django 4.2.13 on 2025-05-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_respuesta_encuesta'),
    ]

    operations = [
    migrations.AlterField(
        model_name='respuesta',
        name='encuesta',
        field=models.ForeignKey(
            to='core.Encuesta',
            on_delete=django.db.models.deletion.SET_NULL,
            null=True,
            blank=True,
            related_name='respuestas'
        ),
    ),
]
