# Generated by Django 4.2.13 on 2025-05-21 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_respuesta_encuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta GD',
                'verbose_name_plural': 'Encuestas GD',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de la pregunta')),
                ('dimension', models.CharField(max_length=100, verbose_name='Dimensión')),
                ('nivel', models.CharField(choices=[('inicial', 'Inicial'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('optimo', 'Óptimo')], max_length=20, verbose_name='Nivel de madurez')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Peso de la pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta GD',
                'verbose_name_plural': 'Preguntas GD',
                'ordering': ['dimension', 'nivel', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('inicial', 'Inicial'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('optimo', 'Óptimo')], max_length=20, verbose_name='Nivel seleccionado')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.encuestagd')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntagd')),
            ],
            options={
                'verbose_name': 'Respuesta GD',
                'verbose_name_plural': 'Respuestas GD',
                'unique_together': {('encuesta', 'pregunta')},
            },
        ),
    ]
