# Generated by Django 4.2.13 on 2025-05-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_encuestagd_preguntagd_respuestagd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestagd',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preguntagd',
            options={'ordering': ['grupo', 'categoria', 'area', 'numero'], 'verbose_name': 'Pregunta GD', 'verbose_name_plural': 'Preguntas GD'},
        ),
        migrations.RemoveField(
            model_name='preguntagd',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='preguntagd',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='respuestagd',
            name='valor',
        ),
        migrations.AddField(
            model_name='preguntagd',
            name='area',
            field=models.CharField(default=1, help_text='Ej. AP2.3.1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntagd',
            name='categoria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntagd',
            name='grupo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntagd',
            name='numero',
            field=models.PositiveIntegerField(default=0, help_text='Número de afirmación en el área'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntagd',
            name='peso_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso del área (suma 100 por categoría)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestagd',
            name='valoracion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No cumple'), (2, 'Consciente'), (3, 'Implantando'), (4, 'Operativo')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntagd',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='preguntagd',
            name='nivel',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('gestionado', 'Gestionado'), ('definido', 'Definido'), ('medido', 'Medido'), ('optimo', 'Óptimo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntagd',
            name='texto',
            field=models.TextField(),
        ),
    ]
