# Generated by Django 4.2.13 on 2025-05-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_encuestagd_options_alter_preguntagd_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestagd',
            options={'ordering': ['-fecha'], 'verbose_name': 'Encuesta GD', 'verbose_name_plural': 'Encuestas GD'},
        ),
    ]
