# Generated by Django 4.2.13 on 2025-05-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_encuestagd_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['codigo'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='valor',
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Texto de la opción')),
                ('puntaje', models.DecimalField(decimal_places=2, help_text='Peso/puntaje que aporta esta opción al total.', max_digits=5, verbose_name='Puntaje de la opción')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que aparece la opción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Preguntas',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='opcion',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.opcionpregunta'),
            preserve_default=False,
        ),
    ]
