# Generated by Django 4.2.13 on 2025-05-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pregunta_options_remove_respuesta_valor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionpregunta',
            options={'ordering': ['pregunta__dimension', 'pregunta__codigo', 'orden'], 'verbose_name': 'Opción de Pregunta', 'verbose_name_plural': 'Opciones de Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['dimension', 'codigo'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
    ]
