# Generated by Django 4.2.13 on 2025-05-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_opcionpregunta_options_alter_pregunta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='id',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de pregunta'),
        ),
    ]
