# Generated by Django 4.2.13 on 2025-06-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_pregunta_id_alter_pregunta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntagd',
            name='area',
            field=models.CharField(help_text='Ej. AP2.3.1', max_length=200),
        ),
        migrations.AlterField(
            model_name='preguntagd',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preguntagd',
            name='grupo',
            field=models.CharField(max_length=200),
        ),
    ]
