# Generated by Django 4.2.13 on 2025-06-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_preguntagd_area_alter_preguntagd_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntagd',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
