# Generated by Django 4.2.13 on 2025-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_preguntagd_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntagd',
            name='nivel',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20),
        ),
    ]
