# Generated by Django 4.2.13 on 2025-06-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_preguntagd_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntagd',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inicial'), (2, 'Gestionado'), (3, 'Definido'), (4, 'Medido'), (5, 'Optimizado')], max_length=20),
        ),
    ]
