# Generated by Django 4.2.13 on 2025-07-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_preguntagd_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=15, verbose_name='Rut de la empresa'),
        ),
    ]
