# Generated by Django 4.2.13 on 2025-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_perfil_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Rut de la empresa'),
        ),
    ]
