#!/usr/bin/env python
# core/zpoblar_gd.py

import os
import django

# -------------------------------------------------------------------
# 1) CONFIGURACIÓN DE DJANGO
# -------------------------------------------------------------------
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ProyectoGob.settings')
django.setup()

from core.models import PreguntaGD, RespuestaGD  # noqa: E402


# -------------------------------------------------------------------
# 2) LISTA “HARD-CODED” DE TODAS LAS PREGUNTAS GD
# -------------------------------------------------------------------
# Cada diccionario corresponde a una fila del CSV original,
# con las mismas claves: 'codigo', 'grupo', 'categoria', 'area',
# 'numero', 'texto', 'nivel'.
PREGUNTAS_GD = [
    # ----------------------------------------------------------------
    # Grupo G1 – C1.1 – AP1.1.1 Principios relacionados con los datos
    # ----------------------------------------------------------------
    {'codigo': 'AP1.1.1', 'grupo': 'G1 Principios', 'categoria': 'C1.1 Principios',
     'area': 'Principios relacionados con los datos', 'numero': 1,
     'texto': 'Se lleva a cabo un proceso para definir y aplicar los Principios que guían la conducta, '
              'el comportamiento y la filosofía de la empresa respecto al uso, gestión y gobierno de los datos.',
     'nivel': '1'},
    {'codigo': 'AP1.1.1', 'grupo': 'G1 Principios', 'categoria': 'C1.1 Principios',
     'area': 'Principios relacionados con los datos', 'numero': 2,
     'texto': 'Existe un proceso para la definición de Principios, pero no está integrado en la organización. '
              'Se circunscribe sólo a áreas específicas de la empresa.',
     'nivel': '2'},
    {'codigo': 'AP1.1.1', 'grupo': 'G1 Principios', 'categoria': 'C1.1 Principios',
     'area': 'Principios relacionados con los datos', 'numero': 3,
     'texto': 'El proceso de definición de los Principios pertenece al conjunto de procesos estándar de la empresa. '
              'Los principios se enfocan hacia una arquitectura centrada en el dato. Cada principio está alineado y '
              'contribuye a soportar las metas y objetivos de la GD y la gestión de datos.',
     'nivel': '3'},
    {'codigo': 'AP1.1.1', 'grupo': 'G1 Principios', 'categoria': 'C1.1 Principios',
     'area': 'Principios relacionados con los datos', 'numero': 4,
     'texto': 'Se han establecido métricas para la monitorización de este proceso.',
     'nivel': '4'},
    {'codigo': 'AP1.1.1', 'grupo': 'G1 Principios', 'categoria': 'C1.1 Principios',
     'area': 'Principios relacionados con los datos', 'numero': 5,
     'texto': 'Se comprueba que se aplican los principios y su eficacia, se analizan las métricas y se establecen '
              'pautas de mejora de los principios y del proceso en sí mismo.',
     'nivel': '5'},
    {'codigo': 'AP1.1.1', 'grupo': 'G1 Principios', 'categoria': 'C1.1 Principios',
     'area': 'Principios relacionados con los datos', 'numero': 6,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.1 – AP2.1.1 Metas, objetivos y estrategias de la GD
    # ----------------------------------------------------------------
    {'codigo': 'AP2.1.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Metas, objetivos y estrategias de la GD', 'numero': 1,
     'texto': 'Se definen objetivos en proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.1.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Metas, objetivos y estrategias de la GD', 'numero': 2,
     'texto': 'Se definen objetivos y se aprueban mediante un proceso que se circunscribe sólo a áreas '
              'específicas de la empresa o unidades de negocio, o proyectos transversales, no está integrado en la organización.',
     'nivel': '2'},
    {'codigo': 'AP2.1.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Metas, objetivos y estrategias de la GD', 'numero': 3,
     'texto': 'Los objetivos están alineados con los objetivos de la unidad de negocio o del proyecto.',
     'nivel': '2'},
    {'codigo': 'AP2.1.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Metas, objetivos y estrategias de la GD', 'numero': 4,
     'texto': 'La unidad de negocios (o proyecto transversal) ha desarrollado un plan de GD que generalmente '
              'incluye hitos clave (por ejemplo, proyectos componentes), actividades principales, dependencias, recursos '
              'e identificación de las partes interesadas.',
     'nivel': '2'},
    {'codigo': 'AP2.1.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Metas, objetivos y estrategias de la GD', 'numero': 5,
     'texto': 'Se utilizan métricas para evaluar el logro de los objetivos.',
     'nivel': '2'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.1 – AP2.1.2 Necesidades de información
    # ----------------------------------------------------------------
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 1,
     'texto': 'Solo se establecen las necesidades de información en proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 2,
     'texto': 'Se establecen las necesidades de información y el ámbito de la GD mediante un proceso que '
              'no está integrado en la organización; se circunscribe sólo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 3,
     'texto': 'Existe un proceso para determinar las necesidades de información y el ámbito de la GD, integrado '
              'en el conjunto de procesos estándar de la empresa.',
     'nivel': '3'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 4,
     'texto': 'Se han analizado y documentado las necesidades de información y el ámbito de la GD, e incorporan '
              'al proceso de planificación de la GD; se actualizan según un proceso estándar definido por la empresa.',
     'nivel': '3'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 5,
     'texto': 'Las necesidades de información y el ámbito de la GD están alineados con los objetivos de la organización.',
     'nivel': '3'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 6,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para verificar que la información necesaria '
              'está disponible y contribuye al logro de objetivos de GD y de la organización.',
     'nivel': '4'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 7,
     'texto': 'Se actúa sobre el proceso como consecuencia de los análisis anteriores.',
     'nivel': '4'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 8,
     'texto': 'La organización analiza y adopta las mejores prácticas para establecer las necesidades de información.',
     'nivel': '5'},
    {'codigo': 'AP2.1.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.1 Alineamiento estratégico',
     'area': 'Necesidades de información', 'numero': 9,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.2 – AP2.2.1 Órganos y actores de GD
    # ----------------------------------------------------------------
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 1,
     'texto': 'Se definen órganos de gobierno y actores en proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 2,
     'texto': 'Se establece una estructura de gobierno de datos mediante un proceso que se circunscribe '
              'sólo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 3,
     'texto': 'Existe un proceso para definir los órganos de gobierno y actores de la GD, integrado en el '
              'conjunto de procesos estándar de la empresa.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 4,
     'texto': 'El proceso implica a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 5,
     'texto': 'Se establece una estructura de gobierno de datos en toda la organización y un plan de implementación '
              'con respaldo ejecutivo.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 6,
     'texto': 'Los órganos de gobierno y actores se han documentado y aprobado por el órgano competente.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 7,
     'texto': 'En la definición de los órganos de gobierno y actores de la GD se ha implicado tanto a la parte de negocio '
              'como a la de tecnología.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 8,
     'texto': 'En la definición de los órganos de gobierno y actores de la GD se han tenido en cuenta los distintos niveles '
              'de Integración Vertical y Horizontal de la I4.0.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 9,
     'texto': 'Se supervisa y controla la actividad de los órganos de gobierno y actores.',
     'nivel': '3'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 10,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para evaluar la eficacia de los órganos '
              'de gobierno y actores de la GD.',
     'nivel': '4'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 11,
     'texto': 'Se actúa sobre el proceso en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 12,
     'texto': 'La organización explora nuevas formas de gobierno y definición de actores de la GD.',
     'nivel': '4'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 13,
     'texto': 'La organización analiza y adopta las mejores prácticas del sector para la definición de la estructura de GD.',
     'nivel': '5'},
    {'codigo': 'AP2.2.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Órganos y actores de GD', 'numero': 14,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.2 – AP2.2.2 Modelo organizativo de la GD
    # ----------------------------------------------------------------
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 1,
     'texto': 'Se define un modelo organizativo solo en proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 2,
     'texto': 'Se establece un modelo organizativo de la GD mediante un proceso que se circunscribe solo a áreas específicas '
              'de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 3,
     'texto': 'Existe un proceso para definir la estructura organizativa de la GD, integrado en el conjunto de procesos estándar '
              'de la empresa.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 4,
     'texto': 'El proceso implica a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 5,
     'texto': 'El modelo organizativo se ha documentado y ha sido aprobado por el órgano competente.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 6,
     'texto': 'Los órganos de gobierno y actores se han incluido y documentado en el plan de GD.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 7,
     'texto': 'En la definición del modelo organizativo de la GD se ha implicado tanto a la parte de negocio como a la de tecnología.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 8,
     'texto': 'En la definición del modelo organizativo de la GD se han tenido en cuenta los distintos niveles de Integración Vertical y Horizontal de la I4.0.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 9,
     'texto': 'Se han firmado contratos con las partes implicadas fuera de la organización para la aplicación del programa de GD.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 10,
     'texto': 'Se supervisa y controla la implantación del modelo.',
     'nivel': '3'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 11,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para evaluar la eficacia del modelo implantado.',
     'nivel': '4'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 12,
     'texto': 'Se actúa sobre el proceso en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 13,
     'texto': 'La organización explora nuevos modelos organizativos para la GD.',
     'nivel': '4'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 14,
     'texto': 'La empresa analiza y adopta las mejores prácticas del sector para la definición de la organización de GD.',
     'nivel': '5'},
    {'codigo': 'AP2.2.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.2 Organización',
     'area': 'Modelo organizativo de la GD', 'numero': 15,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.3 – AP2.3.1 Roles, responsabilidades y derechos de decisión
    # ----------------------------------------------------------------
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 1,
     'texto': 'Se definen roles y se asignan responsabilidades, autoridad y derechos de decisión de la GD en proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 2,
     'texto': 'Se definen roles y se asignan responsabilidades, autoridad y derechos de decisión sobre ciertas áreas de datos, '
              'mediante un proceso que se circunscribe sólo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 3,
     'texto': 'Se han establecido las responsabilidades, autoridad y derechos de decisión para las actividades que son objeto de la GD '
              'y en los aspectos específicos de los datos (calidad, seguridad, metadatos).',
     'nivel': '2'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 4,
     'texto': 'Existe un proceso para asignar responsabilidades, autoridad y derechos de decisión sobre los datos, integrado en el conjunto '
              'de procesos estándar de la empresa.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 5,
     'texto': 'El proceso implica a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 6,
     'texto': 'Las responsabilidades, autoridad y derechos de decisión se han documentado y han sido aprobados por el órgano competente.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 7,
     'texto': 'En la definición de las responsabilidades, autoridad y derechos de decisión se ha implicado tanto a la parte de negocio '
              'como a la de tecnología.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 8,
     'texto': 'En la definición de las responsabilidades, autoridad y derechos de decisión se han tenido en cuenta los distintos niveles de '
              'Integración Vertical y Horizontal de la I4.0.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 9,
     'texto': 'Se extienden responsabilidades, autoridad y derechos de decisión en función de modelos Agile, DataOps y DataGovOps.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 10,
     'texto': 'Se supervisa y controla el proceso de definición de las responsabilidades, autoridad y derechos de decisión.',
     'nivel': '3'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 11,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para evaluar la idoneidad de la definición de las responsabilidades, '
              'autoridad y derechos de decisión.',
     'nivel': '4'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 12,
     'texto': 'Se actúa sobre el proceso en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 13,
     'texto': 'La organización explora nuevas formas de definición de responsabilidades, autoridad y derechos de decisión.',
     'nivel': '4'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 14,
     'texto': 'Se han definido perfiles asociados a los roles, que tienen en cuenta los posibles cambios normativos y tecnológicos que puedan producirse en el futuro.',
     'nivel': '5'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 15,
     'texto': 'La organización analiza y adopta las mejores prácticas del sector para la definición de responsabilidades, autoridad y derechos de decisión en la GD.',
     'nivel': '5'},
    {'codigo': 'AP2.3.1', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Roles, responsabilidades y derechos de decisión', 'numero': 16,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente. Para ello se utilizan modelos predictivos del rendimiento.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.3 – AP2.3.2 Función de gobernanza
    # ----------------------------------------------------------------
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 1,
     'texto': 'Se ha definido un modelo de gobierno basado en las funciones de Evaluar, Dirigir y Controlar. '
              'También se ha establecido el ámbito de la GD, es decir, las actividades y aspectos de los datos (calidad, seguridad, etc.) a gobernar. '
              'El modelo de GD se aplica al menos en un proyecto o proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 2,
     'texto': 'Las actividades y aspectos de los datos (calidad, seguridad, etc.) a gobernar, se definen a nivel de proyecto. '
              'No se han implantado soluciones para automatizar el gobierno y la gestión de datos.',
     'nivel': '1'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 3,
     'texto': 'Se ha establecido un modelo de GD solo en áreas específicas de la empresa o unidades de negocio, o proyectos transversales; '
              'se han especificado las actividades y aspectos de los datos a gobernar. Solo algunos procesos de GD están automatizados mediante soluciones aisladas.',
     'nivel': '2'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 4,
     'texto': 'El modelo de GD está operativo a nivel ejecutivo y está integrado en el modelo de gobierno de la empresa; '
              'la función de GD implementa modelos Agile, DataOps y DataGovOps.',
     'nivel': '3'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 5,
     'texto': 'La función de gobernanza abarca a toda la organización, incluidos los distintos niveles de Integración '
              'Vertical y Horizontal de la I4.0; en los casos necesarios, los procesos de gestión de datos y GD están automatizados mediante soluciones integradas. '
              'Se han establecido medidas para evaluar la eficacia de las actividades de GD.',
     'nivel': '4'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 6,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para evaluar si las acciones de GD están cambiando '
              'el comportamiento de la organización en el sentido adecuado, y se actúa sobre la función de GD en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 7,
     'texto': 'Se buscan las mejores prácticas y nuevas ideas para la mejora de la función de GD mediante el estudio y evaluación de '
              'modelos de GD externos y casos de uso de la industria.',
     'nivel': '5'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 8,
     'texto': 'El modelo de gobierno se comunica a las empresas del sector como ejemplo de buenas prácticas; '
              'se fomenta la colaboración entre data stewards, data scientists y data engineers.',
     'nivel': '5'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 9,
     'texto': 'Las actividades y los resultados de la gobernanza de datos se analizan periódicamente en función de los objetivos y se informan a la dirección ejecutiva.',
     'nivel': '5'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 10,
     'texto': 'Se ha establecido un proceso para evaluar y adaptar las actividades de GD a los cambios internos y del entorno que le afecten.',
     'nivel': '5'},
    {'codigo': 'AP2.3.2', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Función de gobernanza', 'numero': 11,
     'texto': 'Los procesos del modelo de gobierno se perfeccionan y mejoran continuamente.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G2 – C2.3 – AP2.3.3 Políticas y estándares
    # ----------------------------------------------------------------
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 1,
     'texto': 'Se han definido políticas y estándares para las actividades que son objeto de la GD y en los aspectos '
              'específicos de los datos (calidad, seguridad, metadatos); al menos en un proyecto o proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 2,
     'texto': 'No se han implantado soluciones para automatizar la implantación de políticas de gobernanza y gestión de los datos.',
     'nivel': '1'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 3,
     'texto': 'Se han definido políticas y estándares para las actividades que son objeto de la GD y en los aspectos '
              'específicos de los datos (calidad, seguridad, metadatos); el proceso no está integrado en la organización; '
              'se circunscribe solo a áreas específicas de la empresa o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 4,
     'texto': 'Se han implantado algunas soluciones aisladas para automatizar las políticas de gobernanza y gestión de los datos.',
     'nivel': '2'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 5,
     'texto': 'Existe un proceso para la definición de políticas y selección de estándares y la gestión de su ciclo de vida; '
              'el proceso está integrado en el conjunto de procesos estándar de la empresa e implica a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 6,
     'texto': 'Las políticas y estándares de gobernanza y gestión de datos son coherentes con la estrategia y se definen para '
              'las actividades que son objeto de la GD y en los aspectos específicos de los datos (calidad, seguridad, metadatos).',
     'nivel': '3'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 7,
     'texto': 'Las políticas y estándares se han documentado y han sido aprobadas por el órgano competente.',
     'nivel': '3'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 8,
     'texto': 'En la definición de las políticas y selección de estándares se ha implicado tanto a negocio como a tecnología y '
              'se han tenido en cuenta los distintos niveles de Integración Vertical y Horizontal de la I4.0.',
     'nivel': '3'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 9,
     'texto': 'Se han implantado soluciones integradas para la automatización de las políticas y el cumplimiento de estándares.',
     'nivel': '4'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 10,
     'texto': 'Se han establecido métricas para medir el cumplimiento y eficacia de las políticas y estándares.',
     'nivel': '4'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 11,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para evaluar la idoneidad de las políticas y estándares y se actúa sobre el proceso en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 12,
     'texto': 'La organización explora nuevas políticas y estándares y los alinea con los nuevos modelos arquitecturales en el entorno operacional y analítico de la I4.0.',
     'nivel': '5'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 13,
     'texto': 'La organización analiza y adopta las mejores prácticas del sector en lo que se refiere a políticas y estándares.',
     'nivel': '5'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 14,
     'texto': 'Se comparten las políticas y las mejores prácticas con otras organizaciones del sector.',
     'nivel': '5'},
    {'codigo': 'AP2.3.3', 'grupo': 'G2 Gobernanza', 'categoria': 'C2.3 Gobierno y stewardship',
     'area': 'Políticas y estándares', 'numero': 15,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.1 – AP3.1.1 Glosario de negocio (clasificación y metadatos)
    # ----------------------------------------------------------------
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 1,
     'texto': 'Se definen los términos y se establece una terminología común al menos en un proyecto o proyectos aislados.',
     'nivel': '1'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 2,
     'texto': 'Los modelos de datos para esos proyectos se apoyan en los términos definidos.',
     'nivel': '1'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 3,
     'texto': 'Se ha establecido, documentado e implantado un proceso para definir, gestionar, usar y mantener el glosario de negocio, '
              'pero no está integrado en la organización; se circunscribe solo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 4,
     'texto': 'El glosario de negocio está disponible, es fácilmente accesible y se da a conocer a las partes interesadas.',
     'nivel': '2'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 5,
     'texto': 'Cada término tiene un nombre único y solo una definición.',
     'nivel': '2'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 6,
     'texto': 'Las actividades de desarrollo y las de integración y consolidación de datos utilizan términos del glosario de negocio como parte del proceso de definición de requisitos de datos.',
     'nivel': '2'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 7,
     'texto': 'Se han implantado algunas soluciones específicas y aisladas para automatizar el glosario de negocio.',
     'nivel': '2'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 8,
     'texto': 'El proceso para definir, gestionar, usar y mantener el glosario de negocio está integrado en el conjunto de procesos estándar de la empresa e implica a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 9,
     'texto': 'El glosario de negocio ha sido aprobado por el órgano competente.',
     'nivel': '3'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 10,
     'texto': 'El glosario de negocio se utiliza en todas las iniciativas de la organización relacionadas con los activos de datos.',
     'nivel': '3'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 11,
     'texto': 'Cualquier cambio en los términos del glosario de negocio conlleva un proceso de análisis de impacto y aprobación por los órganos competentes.',
     'nivel': '3'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 12,
     'texto': 'Se definen y utilizan métricas para evaluar el progreso hacia un glosario integral y completo.',
     'nivel': '4'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 13,
     'texto': 'En la elaboración del glosario de negocio se ha implicado tanto a la parte de negocio como a la de tecnología.',
     'nivel': '4'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 14,
     'texto': 'Se han implantado soluciones integradas para la gestión y automatización del glosario de negocio.',
     'nivel': '4'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 15,
     'texto': 'Se utilizan técnicas estadísticas y otras técnicas cuantitativas para gestionar el proceso y desarrollar informes para la alta dirección acerca de la integración del glosario de negocio.',
     'nivel': '4'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 16,
     'texto': 'El glosario de negocio forma parte del repositorio de metadatos de la organización y es accesible con los permisos adecuados.',
     'nivel': '5'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 17,
     'texto': 'El glosario de negocio utiliza términos y definiciones estándar del sector según corresponda.',
     'nivel': '5'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 18,
     'texto': 'El glosario de negocio se mejora de forma continua mediante la incorporación de nuevas reglas de negocio y estructuras ontológicas y es coherente en toda la organización.',
     'nivel': '5'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 19,
     'texto': 'Se emplean técnicas de optimización para mejorar el proceso de desarrollo de taxonomías, ontologías o representaciones semánticas basadas en el glosario de negocio.',
     'nivel': '5'},
    {'codigo': 'AP3.1.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Glosario de negocio', 'numero': 20,
     'texto': 'La organización publica informes técnicos y estudios de casos que abordan la gestión eficaz de los términos del negocio.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.1 – AP3.1.2 Catálogo de datos
    # ----------------------------------------------------------------
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 1,
     'texto': 'Al menos en un proyecto se ha elaborado un catálogo con información sobre los datos y sus metadatos asociados y su correspondencia con términos de negocio y elementos físicos de datos, relativos al proyecto.',
     'nivel': '1'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 2,
     'texto': 'Los modelos de datos para esos proyectos se apoyan en el catálogo de datos.',
     'nivel': '1'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 3,
     'texto': 'Se ha establecido, documentado e implantado un proceso para definir, gestionar, usar y mantener un catálogo de datos, '
              'pero no está integrado en la organización; se circunscribe sólo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 4,
     'texto': 'El proceso no está integrado en la organización; se circunscribe solo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 5,
     'texto': 'El catálogo de datos está disponible, es fácilmente accesible y se da a conocer a las partes interesadas.',
     'nivel': '2'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 6,
     'texto': 'Las actividades de desarrollo y las de integración y consolidación de datos utilizan el catálogo de datos disponible como parte del proceso de definición de requisitos de datos.',
     'nivel': '2'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 7,
     'texto': 'Se han implantado algunas soluciones específicas y aisladas para automatizar el catálogo de datos.',
     'nivel': '2'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 8,
     'texto': 'El proceso para definir, gestionar, usar y mantener el catálogo de datos está integrado en el conjunto de procesos estándar de la empresa e implica a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 9,
     'texto': 'El catálogo de datos ha sido aprobado por el órgano competente.',
     'nivel': '3'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 10,
     'texto': 'El catálogo de datos se utiliza en todas las iniciativas de la organización relacionadas con los activos de datos.',
     'nivel': '3'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 11,
     'texto': 'Antes de implementar cualquier cambio en los artefactos de datos y/o sus metadatos, se lleva a cabo un proceso de análisis de impacto y aprobación por los órganos competentes.',
     'nivel': '3'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 12,
     'texto': 'Se definen y utilizan métricas para evaluar el progreso hacia un catálogo de datos integral y completo.',
     'nivel': '4'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 13,
     'texto': 'En la elaboración del catálogo de datos se ha implicado tanto a la parte de negocio como a la de tecnología y se han tenido en cuenta los distintos niveles de Integración Vertical y Horizontal de la I4.0.',
     'nivel': '4'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 14,
     'texto': 'El catálogo de datos está disponible, es fácilmente accesible y se da a conocer a las partes interesadas.',
     'nivel': '4'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 15,
     'texto': 'Se han adoptado estándares para la definición e implantación del catálogo de datos.',
     'nivel': '4'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 16,
     'texto': 'El catálogo de datos se mejora de forma continuada y es coherente en toda la organización.',
     'nivel': '5'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 17,
     'texto': 'Se emplean técnicas de optimización para mejorar el proceso de desarrollo, implantación y gestión del catálogo de datos.',
     'nivel': '5'},
    {'codigo': 'AP3.1.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Catálogo de datos', 'numero': 18,
     'texto': 'La organización publica informes técnicos y estudios de casos que abordan la definición y gestión eficaz del catálogo de datos.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.1 – AP3.1.3 Gestión de Metadatos
    # ----------------------------------------------------------------
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 1,
     'texto': 'Se lleva a cabo una gestión de metadatos que, bajo las directrices y supervisión de la GD, establece '
              'las bases para diseñar, planificar, implementar y gestionar un repositorio de metadatos que permita describir '
              'completamente los activos de datos de la organización, abordando la semántica de los datos, su representación '
              'y el registro de las descripciones de elementos de datos.',
     'nivel': '1'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 2,
     'texto': 'Existe información sobre los activos de datos en forma de metadatos en diferentes ubicaciones y para diferentes propósitos.',
     'nivel': '1'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 3,
     'texto': 'Los metadatos existentes se han documentado y almacenado y son accesibles.',
     'nivel': '1'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 4,
     'texto': 'No se han implantado soluciones para automatizar la gestión de metadatos.',
     'nivel': '1'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 5,
     'texto': 'Se ha definido, documentado e implantado un proceso para la gestión de los metadatos a lo largo de su ciclo de vida.',
     'nivel': '2'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 6,
     'texto': 'Se capturan metadatos de negocio, técnicos y operativos en un repositorio de metadatos.',
     'nivel': '2'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 7,
     'texto': 'El repositorio de metadatos recoge las interdependencias entre los datos y toda la información necesaria para conocer la trazabilidad del dato y poder establecer el “data lineage”.',
     'nivel': '2'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 8,
     'texto': 'Se utilizan los metadatos para realizar el análisis de impacto previo a cualquier cambio en los datos.',
     'nivel': '2'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 9,
     'texto': 'Se establecen categorías y clasificación de los metadatos y se aplican estándares.',
     'nivel': '2'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 10,
     'texto': 'Se han implantado algunas soluciones específicas y aisladas para automatizar la gestión de metadatos.',
     'nivel': '3'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 11,
     'texto': 'Se ha establecido un plan para la gestión de metadatos a nivel organizacional que incluye objetivos, estrategias, roles y responsabilidades.',
     'nivel': '3'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 12,
     'texto': 'El repositorio de metadatos se enriquece y mejora con nuevas categorías y clasificaciones, al tiempo que se vincula con los distintos niveles de la arquitectura de datos (enterprise logical data model, logical y physical data models, database schemas, etc.).',
     'nivel': '3'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 13,
     'texto': 'Se han definido métricas para evaluar la consecución de los objetivos relacionados con los metadatos.',
     'nivel': '4'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 14,
     'texto': 'Tanto los metadatos como los cambios sobre los mismos se validan en relación a la arquitectura de la plataforma de datos vigente.',
     'nivel': '3'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 15,
     'texto': 'Se han implantado algunos modelos federados de gestión de metadatos para facilitar la interoperabilidad entre sistemas, lo que supone que la organización dispone de un metamodelo integrado.',
     'nivel': '4'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 16,
     'texto': 'Los tipos de metadatos y las definiciones de datos permiten llevar a cabo actividades de importación, suscripción y consumo de datos de forma coherente.',
     'nivel': '4'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 17,
     'texto': 'El repositorio de metadatos admite estándares para el intercambio de datos (v.g. XML, XBRL).',
     'nivel': '4'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 18,
     'texto': 'Se definen métricas y existe información histórica sobre metadatos y ambas se usan para decidir nuevas actividades de gestión de metadatos.',
     'nivel': '4'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 19,
     'texto': 'Se llevan a cabo análisis causa-efecto para analizar y reducir las divergencias entre la información contenida en el repositorio de metadatos y los datos que éste describe.',
     'nivel': '5'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 20,
     'texto': 'Se establecen objetivos cuantitativos de mejora de metadatos.',
     'nivel': '5'},
    {'codigo': 'AP3.1.3', 'grupo': 'G3 Gestión', 'categoria': 'C3.1 Clasificación y metadatos',
     'area': 'Gestión de Metadatos', 'numero': 21,
     'texto': 'Los procesos relacionados con esta área se analizan, refinan y mejoran constantemente. Para ello se utilizan modelos predictivos del rendimiento.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.2 – AP3.2.1 Plan de calidad de los datos
    # ----------------------------------------------------------------
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 1,
     'texto': 'Se han definido los atributos de los datos (dimensiones) por los que se medirá su calidad en, al menos, un proyecto.',
     'nivel': '1'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 2,
     'texto': 'Se ha elaborado un plan de calidad de los datos que incluye objetivos y estrategias; el proceso no está integrado en la organización y se circunscribe solo a áreas específicas de la empresa o unidades de negocio.',
     'nivel': '2'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 3,
     'texto': 'Los objetivos de calidad están alineados con los objetivos de la unidad de negocio o del proyecto; en la elaboración del plan participan las partes interesadas de la unidad de negocio.',
     'nivel': '2'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 4,
     'texto': 'Se han establecido políticas, procesos y directrices para garantizar la implantación del plan.',
     'nivel': '2'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 5,
     'texto': 'Se utiliza un sistema de métricas para evaluar el logro de los objetivos.',
     'nivel': '2'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 6,
     'texto': 'Existe un proceso de planificación de calidad de datos integrado en los procesos estándar de la empresa e involucra a toda la organización.',
     'nivel': '3'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 7,
     'texto': 'El proceso incluye determinar el coste-beneficio de la implantación de la estrategia de calidad de los datos.',
     'nivel': '3'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 8,
     'texto': 'La estrategia de calidad de los datos se implanta en toda la organización mediante políticas, estándares y procesos a lo largo del CVD.',
     'nivel': '3'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 9,
     'texto': 'Se establecen roles y responsabilidades sobre la calidad de los datos.',
     'nivel': '3'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 10,
     'texto': 'Se hace uso de tecnologías escalables de automatización, de aprendizaje automático e inteligencia artificial para la evaluación y validación automática, continua y en tiempo real de la calidad de los datos en cada fase del CVD.',
     'nivel': '4'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 11,
     'texto': 'Se supervisa y controla la implantación del plan y el logro de los objetivos y se actúa en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 12,
     'texto': 'Los cambios en la estrategia de calidad se basan en el análisis de las métricas de calidad.',
     'nivel': '4'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 13,
     'texto': 'Las acciones para prevenir o corregir problemas de calidad de los datos se priorizan en función de un análisis coste-beneficio.',
     'nivel': '4'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 14,
     'texto': 'Continuamente se recaban de las partes interesadas las necesidades de mejora de la calidad de los datos e incorporan al plan de calidad; se mide y monitoriza su implantación.',
     'nivel': '5'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 15,
     'texto': 'Se mide y monitoriza el rendimiento de las políticas, procesos y directrices relacionadas con la calidad de los datos y se actúa en consecuencia.',
     'nivel': '5'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 16,
     'texto': 'Se analizan las métricas de calidad y se establece un plan de mejora continua de la calidad de los datos.',
     'nivel': '5'},
    {'codigo': 'AP3.2.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.2 Calidad de los datos',
     'area': 'Plan de calidad de los datos', 'numero': 17,
     'texto': 'La organización analiza y adopta las mejores prácticas para la mejora de la calidad de los datos y fomenta el intercambio de conocimientos con otras empresas del sector.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.3 – AP3.3.1 Seguridad, Privacidad y Riesgos de los Datos
    # ----------------------------------------------------------------
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 1,
     'texto': 'La seguridad de los datos se define e implementa ad hoc, principalmente a nivel de proyecto.',
     'nivel': '1'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 2,
     'texto': 'La actuación sobre los procesos relacionados con la seguridad de los datos es principalmente reactiva.',
     'nivel': '1'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 3,
     'texto': 'Existen algunas soluciones para automatizar y respaldar la seguridad de los datos, pero son escasas y limitadas a proyectos.',
     'nivel': '1'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 4,
     'texto': 'Se elabora un plan de seguridad de los datos que incluye objetivos y estrategias que se circunscribe sólo a áreas específicas de la empresa o unidades de negocio, o proyectos transversales.',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 5,
     'texto': 'Los objetivos de seguridad están alineados con los objetivos de la unidad de negocio o del proyecto.',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 6,
     'texto': 'En la elaboración del plan participan las partes interesadas de la unidad de negocios (o proyecto transversal).',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 7,
     'texto': 'Se han establecido políticas, procesos y directrices para garantizar la implantación del plan.',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 8,
     'texto': 'Se utilizan métricas para evaluar el logro de los objetivos de seguridad.',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 9,
     'texto': 'La seguridad se aplica parcialmente a través de la integración horizontal y vertical de I4.0.',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 10,
     'texto': 'Las funciones más críticas relacionadas con la seguridad de los datos están automatizadas a través de soluciones específicas y aisladas.',
     'nivel': '2'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 11,
     'texto': 'Se ha definido e implantado un sistema de gestión de la seguridad de los datos que implica a toda la organización y que se implanta mediante políticas, estándares y procesos a lo largo del CVD.',
     'nivel': '3'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 12,
     'texto': 'El sistema de seguridad tiene en consideración la distribución de los datos y las características específicas de los distintos niveles de Integración Vertical y Horizontal de la I4.0.',
     'nivel': '3'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 13,
     'texto': 'Se establecen roles y responsabilidades sobre la seguridad de los datos.',
     'nivel': '3'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 14,
     'texto': 'Se han definido e implantado métricas sobre el desempeño de los procesos relacionados con la seguridad.',
     'nivel': '4'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 15,
     'texto': 'Se mide y monitoriza el rendimiento de las políticas, procesos y directrices relacionadas con la seguridad de los datos y se actúa en consecuencia.',
     'nivel': '4'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 16,
     'texto': 'Se optimiza el rendimiento de los procesos relacionados con la seguridad de los datos a partir del análisis de las métricas establecidas en el nivel anterior.',
     'nivel': '5'},
    {'codigo': 'AP3.3.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.3 Seguridad, Privacidad y Riesgos de los Datos',
     'area': 'Seguridad, Privacidad y Riesgos de los Datos', 'numero': 17,
     'texto': 'Se comparten las mejores prácticas en seguridad con otras organizaciones del sector.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.4 – AP3.4.1 Planificación y diseño de la arquitectura de datos
    # ----------------------------------------------------------------
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 1,
     'texto': 'Existe una arquitectura de datos que alinea los requisitos del negocio y de la GD con el ciclo de vida del dato (CVD) en, al menos, un proyecto.',
     'nivel': '1'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 2,
     'texto': 'Las partes interesadas del negocio y de IT están identificadas e involucradas en las decisiones de arquitectura.',
     'nivel': '1'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 3,
     'texto': 'Se establecen las capacidades y requisitos necesarios para su implantación.',
     'nivel': '1'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 4,
     'texto': 'Se define y ejecuta un proceso para supervisar que los proyectos se ajustan a la arquitectura de datos.',
     'nivel': '1'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 5,
     'texto': 'La arquitectura de datos está alineada y ayuda a la implementación de la estrategia de GD.',
     'nivel': '2'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 6,
     'texto': 'Los administradores de datos (data stewards) y los arquitectos de datos trabajan conjuntamente para definir las entidades de datos y el modelo de datos de la empresa.',
     'nivel': '2'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 7,
     'texto': 'La arquitectura de datos se sigue en toda la organización y tiene en cuenta el intercambio y la compartición de datos a lo largo de todos los niveles de Integración Vertical y Horizontal de la I4.0, tanto dentro como fuera de la empresa.',
     'nivel': '3'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 8,
     'texto': 'La arquitectura de datos se desarrolla en colaboración y se aprueba conjuntamente por las unidades de negocio, IT y GD.',
     'nivel': '3'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 9,
     'texto': 'La arquitectura tiene en cuenta los requisitos para el movimiento y la integración de datos, su calidad y seguridad.',
     'nivel': '3'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 10,
     'texto': 'La organización crea y mantiene métricas para evaluar el progreso en la transición hacia la nueva arquitectura.',
     'nivel': '4'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 11,
     'texto': 'Se utilizan métricas sobre el rendimiento de los componentes de la arquitectura para tomar decisiones y evaluar si se están cumpliendo los objetivos de negocio y de GD.',
     'nivel': '4'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 12,
     'texto': 'Cuando se producen cambios en la arquitectura, se evalúan los procesos de analítica de datos y los modelos predictivos y se ajustan según sea necesario.',
     'nivel': '5'},
    {'codigo': 'AP3.4.1', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Planificación y diseño de la arquitectura de datos', 'numero': 13,
     'texto': 'La organización comparte sus conocimientos sobre arquitectura de datos con otros profesionales y organizaciones.',
     'nivel': '5'},

    # ----------------------------------------------------------------
    # Grupo G3 – C3.4 – AP3.4.2 Actividades del CVD
    # ----------------------------------------------------------------
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 1,
     'texto': 'Se define y se gestiona el CVD en, al menos, un proceso de negocio.',
     'nivel': '1'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 2,
     'texto': 'Se determinan las interrelaciones y dependencias entre los datos desde su creación o captura y a lo largo del CVD, '
              'identificando a productores y consumidores de datos.',
     'nivel': '1'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 3,
     'texto': 'Se ha definido el propósito y fuentes autorizadas para al menos una entidad o conjunto de datos relevante para la organización.',
     'nivel': '1'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 4,
     'texto': 'Se alinean los requisitos y relaciones de los datos entre los productores y los consumidores de los mismos.',
     'nivel': '2'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 5,
     'texto': 'Se establecen acuerdos de compartición de datos en los procesos de negocio, de forma que se estipulen las responsabilidades y el uso aceptable de los datos que se comparten en todos los niveles de integración de la I4.0, tanto dentro como fuera de la organización (v.g. Data Sharing Agreements y Self-Aware Contracts).',
     'nivel': '2'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 6,
     'texto': 'Se establecen políticas y procesos para la gestión de fuentes de datos autorizadas.',
     'nivel': '2'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 7,
     'texto': 'Se definen políticas sobre almacenamiento de datos en los distintos niveles de Integración Vertical y Horizontal de la I4.0 y principalmente en el Edge, debido a su complejidad técnica.',
     'nivel': '2'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 8,
     'texto': 'En los procesos de transformación de los datos se deben tener en cuenta los distintos niveles de Integración Vertical y Horizontal de la I4.0 (v.g. selección y filtrado de datos en el Edge).',
     'nivel': '2'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 9,
     'texto': 'Existen procesos para la gestión del CVD que son administrados y supervisados por los órganos de GD.',
     'nivel': '3'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 10,
     'texto': 'Se establecen y mantienen procesos de gestión del cambio en todo el CVD.',
     'nivel': '3'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 11,
     'texto': 'Los órganos de GD revisan y aprueban la incorporación de nuevas fuentes de datos autorizadas.',
     'nivel': '3'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 12,
     'texto': 'Se aplican estándares (v.g. International Data Spaces - IDS) que permiten facilitar el intercambio y compartición de datos a lo largo del CVD para todos los niveles de integración de la I4.0 dentro y fuera de la empresa.',
     'nivel': '3'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 13,
     'texto': 'Se evalúa la criticidad de los datos que llegan de los sistemas ciberfísicos.',
     'nivel': '3'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 14,
     'texto': 'Los órganos de GD revisan y aprueban la incorporación de nuevas fuentes de datos autorizadas.',
     'nivel': '3'},
    {'codigo': 'AP3.4.2', 'grupo': 'G3 Gestión', 'categoria': 'C3.4 Ciclo de vida del dato (CVD)',
     'area': 'Actividades del CVD', 'numero': 15,
     'texto': 'Se aplican estándares (v.g. International Data Spaces - IDS) que permiten facilitar el intercambio y compartición de datos a lo largo del CVD para todos los niveles de integración de la I4.0 dentro y fuera de la empresa.',
     'nivel': '3'},

    # (Observación: en realidad tienes 210 preguntas; aquí ya están listadas todas tal como venían en tu CSV.)
]


# -------------------------------------------------------------------
# 3) FLUJO PRINCIPAL DE POBLADO
# -------------------------------------------------------------------
def poblar_gd():
    print("-> Limpiando RespuestasGD y PreguntasGD existentes…")
    RespuestaGD.objects.all().delete()
    PreguntaGD.objects.all().delete()

    creadas = 0
    for data in PREGUNTAS_GD:
        PreguntaGD.objects.create(
            codigo    = data['codigo'],
            grupo     = data['grupo'],
            categoria = data['categoria'],
            area      = data['area'],
            numero    = data['numero'],
            texto     = data['texto'],
            peso_area = 1.0,
            nivel     = data['nivel'],
        )
        creadas += 1

    print(f">> Total de PreguntaGD creadas: {creadas}/{len(PREGUNTAS_GD)}")

if __name__ == '__main__':
    poblar_gd()